-- MySQL Script generated by MySQL Workbench
-- Fri Feb 12 15:24:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios` (
  `idfuncionarios` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` INT NOT NULL,
  `funcao` VARCHAR(45) NULL,
  `salario` INT NULL,
  PRIMARY KEY (`idfuncionarios`),
  UNIQUE INDEX `idfuncionarios_UNIQUE` (`idfuncionarios` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Rh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Rh` (
  `idRh` INT NOT NULL,
  `funcionarios_idfuncionarios` INT NOT NULL,
  PRIMARY KEY (`idRh`, `funcionarios_idfuncionarios`),
  INDEX `fk_Rh_funcionarios_idx` (`funcionarios_idfuncionarios` ASC) VISIBLE,
  CONSTRAINT `fk_Rh_funcionarios`
    FOREIGN KEY (`funcionarios_idfuncionarios`)
    REFERENCES `mydb`.`funcionarios` (`idfuncionarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
